# Generated by Django 4.2.7 on 2024-01-22 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_longitude', models.DecimalField(max_digits=9, decimal_places=6)),
                ('location_latitude', models.DecimalField(max_digits=9, decimal_places=6)),
                ('city', models.CharField( max_length=100))
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', related_query_name='place', to='dao.place')), 
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', related_query_name='place', to='dao.business_owner')), 
                ('start_time', models.DateTimeField(editable=True)),
                ('end_time', models.DateTimeField(editable=True)),
                ('description', models.TextField()),
                ('max_ppl', models.IntegerField()),
                ('current_ppl', models.IntegerField()),
                ('score', models.DecimalField(max_digits=5, decimal_places=4)),
                ('average_price', models.DecimalField(max_digits=10, decimal_places=4)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', related_query_name='event_review', to='dao.event')), 
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', related_query_name='event_review', to='dao.client')), 
                ('content', models.TextField()),
                ('rating', models.DecimalField(max_digits=3, decimal_places=2)),
            ],
        ),
