# Generated by Django 4.2.7 on 2024-01-22 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_longitude', models.DecimalField(max_digits=9, decimal_places=6)),
                ('location_latitude', models.DecimalField(max_digits=9, decimal_places=6)),
                ('city', models.CharField( max_length=100))
            ],
        ),


        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='event', to='dao.place')), 
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='event', to='dao.business_owner')), 
                ('start_time', models.DateTimeField(editable=True)),
                ('end_time', models.DateTimeField(editable=True)),
                ('description', models.TextField()),
                ('max_ppl', models.IntegerField()),
                ('current_ppl', models.IntegerField()),
                ('ppl_reviewed', models.IntegerField()),
                ('score', models.DecimalField(max_digits=5, decimal_places=4)),
                ('avg_price', models.DecimalField(max_digits=10, decimal_places=4)),
                ('event_type', models.CharField(max_length=100, choices=[
                    ('dining', 'Dining'),
                    ('outdoor', 'Outdoor'),
                    ('party', 'Party'),
                    ('conference', 'Conference'),
                    ('workshop', 'Workshop'),
                    ('other', 'Other'),
                ])),
            ],
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', related_query_name='event_review', to='dao.event')), 
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', related_query_name='event_review', to='dao.client')), 
                ('content', models.TextField()),
                ('rating', models.CharField(max_digits=1, choice = [
                    (1, '1 - Very Poor'),
                    (2, '2 - Poor'),
                    (3, '3 - Average'),
                    (4, '4 - Good'),
                    (5, '5 - Excellent'),
                ])),
                ('price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True, max_length=20)),
                ('city', models.CharField( max_length=100)),
            ],
        ),

        migrations.CreateModel(
            name='Client',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True)),
                ('city', models.CharField( max_length=100)),
                ('follows', models.ManyToManyField(related_name='followers', related_query_name='follower', to='dao.client')),
                ('added_places', models.ManyToManyField(related_name='added_by_clients', related_query_name='place', to='dao.client')),
            ],
        ),

        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', related_query_name='rsvp', to='dao.event')), 
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', related_query_name='rsvp', to='dao.client')), 
            ],
        ),

        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', related_query_name='save', to='dao.place')), 
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dao.client')),
            ],
        ),

        migrations.AddConstraint(
            model_name = 'rsvp',
            constraint = models.UniqueConstraint(models.F('client'), models.F('event'), name='unique_rsvp'),
        ),

        migrations.AddConstraint(
            model_name = 'save',
            constraint = models.UniqueConstraint(models.F('client'), models.F('place'), name='unique_save'),
        ),
    ]